config/routes.rb
Rails.application.routes.draw do
  root 'purchase_orders#index'

  resources :order_items
  resources :items
  resources :purchase_orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  has_many :order_items, dependent: :destroy

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(_options = {})
    PurchaseOrderDenormalizer.new(self).to_hash
  end

  settings index: { number_of_shards: 1 } do
    mapping dynamic: 'false' do
      indexes :id, type: :integer
      indexes :purchase_date, type: :date, format: :date_optional_time
      indexes :status, type: :keyword
      indexes :sales_channel, type: :keyword
      indexes :num_items_shipped, type: :integer
      indexes :num_items_unshipped, type: :integer
      indexes :payment_method, type: :keyword
      indexes :shipped_at, type: :date, format: :date_optional_time
      indexes :shipping_price, type: :half_float
      indexes :shipping_tax, type: :half_float
      indexes :carrier, type: :keyword
      indexes :tracking_number
      indexes :estimated_arrival_date, type: :date, format: :date_optional_time
      indexes :fulfillment_center, type: :keyword
      indexes :confirmed_at, type: :date, format: :date_optional_time
      indexes :returned_date, type: :date, format: :date_optional_time
      indexes :return_reason
      indexes :notes
      indexes :refunded_at, type: :date, format: :date_optional_time
      indexes :ship_to_name
      indexes :ship_to_address

      indexes :skus
      indexes :item_ids, type: :long

      indexes :unique_products, type: :integer
      indexes :quantity_ordered, type: :integer
      indexes :quantity_shipped, type: :integer
      indexes :quantity_unshipped, type: :integer

      indexes :currency, type: :keyword

      indexes :order_items_info, type: :nested do
        indexes :item_id, type: :integer
        indexes :quantity_ordered, type: :integer
        indexes :quantity_shipped, type: :integer
        indexes :price, type: :half_float
        indexes :discount, type: :half_float
        indexes :tax, type: :half_float
        indexes :platform_fee, type: :half_float

        # extras
        indexes :item_title
        indexes :item_sku
        indexes :item_nickname
      end

    end
  end

end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: %i[ show edit update destroy ]

  # GET /purchase_orders or /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1 or /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders or /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: "Purchase order was successfully created." }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1 or /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: "Purchase order was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1 or /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: "Purchase order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_order_params
      params.require(:purchase_order).permit(:order_num, :purchase_date, :status, :sales_channel, :order_total, :num_items_shipped, :num_items_unshipped, :payment_method, :shipped_at, :shipping_price, :shipping_tax, :carrier, :tracking_number, :estimated_arrival_date, :fulfillment_center, :confirmed_at, :returned_date, :return_reason, :notes, :refunded_at, :ship_to_name, :ship_to_address)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order) do |form| %>
  <% if purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
        <% purchase_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_num %>
    <%= form.text_field :order_num %>
  </div>

  <div class="field">
    <%= form.label :purchase_date %>
    <%= form.datetime_select :purchase_date %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :sales_channel %>
    <%= form.text_field :sales_channel %>
  </div>

  <div class="field">
    <%= form.label :order_total %>
    <%= form.text_field :order_total %>
  </div>

  <div class="field">
    <%= form.label :num_items_shipped %>
    <%= form.number_field :num_items_shipped %>
  </div>

  <div class="field">
    <%= form.label :num_items_unshipped %>
    <%= form.number_field :num_items_unshipped %>
  </div>

  <div class="field">
    <%= form.label :payment_method %>
    <%= form.text_field :payment_method %>
  </div>

  <div class="field">
    <%= form.label :shipped_at %>
    <%= form.datetime_select :shipped_at %>
  </div>

  <div class="field">
    <%= form.label :shipping_price %>
    <%= form.text_field :shipping_price %>
  </div>

  <div class="field">
    <%= form.label :shipping_tax %>
    <%= form.text_field :shipping_tax %>
  </div>

  <div class="field">
    <%= form.label :carrier %>
    <%= form.text_field :carrier %>
  </div>

  <div class="field">
    <%= form.label :tracking_number %>
    <%= form.text_field :tracking_number %>
  </div>

  <div class="field">
    <%= form.label :estimated_arrival_date %>
    <%= form.datetime_select :estimated_arrival_date %>
  </div>

  <div class="field">
    <%= form.label :fulfillment_center %>
    <%= form.text_field :fulfillment_center %>
  </div>

  <div class="field">
    <%= form.label :confirmed_at %>
    <%= form.datetime_select :confirmed_at %>
  </div>

  <div class="field">
    <%= form.label :returned_date %>
    <%= form.datetime_select :returned_date %>
  </div>

  <div class="field">
    <%= form.label :return_reason %>
    <%= form.text_field :return_reason %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :refunded_at %>
    <%= form.datetime_select :refunded_at %>
  </div>

  <div class="field">
    <%= form.label :ship_to_name %>
    <%= form.text_field :ship_to_name %>
  </div>

  <div class="field">
    <%= form.label :ship_to_address %>
    <%= form.text_field :ship_to_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_orders/edit.html.erb
<h1>Editing Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchase Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order num</th>
      <th>Purchase date</th>
      <th>Status</th>
      <th>Sales channel</th>
      <th>Order total</th>
      <th>Num items shipped</th>
      <th>Num items unshipped</th>
      <th>Payment method</th>
      <th>Shipped at</th>
      <th>Shipping price</th>
      <th>Shipping tax</th>
      <th>Carrier</th>
      <th>Tracking number</th>
      <th>Estimated arrival date</th>
      <th>Fulfillment center</th>
      <th>Confirmed at</th>
      <th>Returned date</th>
      <th>Return reason</th>
      <th>Notes</th>
      <th>Refunded at</th>
      <th>Ship to name</th>
      <th>Ship to address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_orders.each do |purchase_order| %>
      <tr>
        <td><%= purchase_order.order_num %></td>
        <td><%= purchase_order.purchase_date %></td>
        <td><%= purchase_order.status %></td>
        <td><%= purchase_order.sales_channel %></td>
        <td><%= purchase_order.order_total %></td>
        <td><%= purchase_order.num_items_shipped %></td>
        <td><%= purchase_order.num_items_unshipped %></td>
        <td><%= purchase_order.payment_method %></td>
        <td><%= purchase_order.shipped_at %></td>
        <td><%= purchase_order.shipping_price %></td>
        <td><%= purchase_order.shipping_tax %></td>
        <td><%= purchase_order.carrier %></td>
        <td><%= purchase_order.tracking_number %></td>
        <td><%= purchase_order.estimated_arrival_date %></td>
        <td><%= purchase_order.fulfillment_center %></td>
        <td><%= purchase_order.confirmed_at %></td>
        <td><%= purchase_order.returned_date %></td>
        <td><%= purchase_order.return_reason %></td>
        <td><%= purchase_order.notes %></td>
        <td><%= purchase_order.refunded_at %></td>
        <td><%= purchase_order.ship_to_name %></td>
        <td><%= purchase_order.ship_to_address %></td>
        <td><%= link_to 'Show', purchase_order %></td>
        <td><%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></td>
        <td><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase Order', new_purchase_order_path %>

app/views/purchase_orders/new.html.erb
<h1>New Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order num:</strong>
  <%= @purchase_order.order_num %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @purchase_order.purchase_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @purchase_order.status %>
</p>

<p>
  <strong>Sales channel:</strong>
  <%= @purchase_order.sales_channel %>
</p>

<p>
  <strong>Order total:</strong>
  <%= @purchase_order.order_total %>
</p>

<p>
  <strong>Num items shipped:</strong>
  <%= @purchase_order.num_items_shipped %>
</p>

<p>
  <strong>Num items unshipped:</strong>
  <%= @purchase_order.num_items_unshipped %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @purchase_order.payment_method %>
</p>

<p>
  <strong>Shipped at:</strong>
  <%= @purchase_order.shipped_at %>
</p>

<p>
  <strong>Shipping price:</strong>
  <%= @purchase_order.shipping_price %>
</p>

<p>
  <strong>Shipping tax:</strong>
  <%= @purchase_order.shipping_tax %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @purchase_order.carrier %>
</p>

<p>
  <strong>Tracking number:</strong>
  <%= @purchase_order.tracking_number %>
</p>

<p>
  <strong>Estimated arrival date:</strong>
  <%= @purchase_order.estimated_arrival_date %>
</p>

<p>
  <strong>Fulfillment center:</strong>
  <%= @purchase_order.fulfillment_center %>
</p>

<p>
  <strong>Confirmed at:</strong>
  <%= @purchase_order.confirmed_at %>
</p>

<p>
  <strong>Returned date:</strong>
  <%= @purchase_order.returned_date %>
</p>

<p>
  <strong>Return reason:</strong>
  <%= @purchase_order.return_reason %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @purchase_order.notes %>
</p>

<p>
  <strong>Refunded at:</strong>
  <%= @purchase_order.refunded_at %>
</p>

<p>
  <strong>Ship to name:</strong>
  <%= @purchase_order.ship_to_name %>
</p>

<p>
  <strong>Ship to address:</strong>
  <%= @purchase_order.ship_to_address %>
</p>

<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>